application:
    title: Guns N Ammo
info:
    app:
        description: Spring boot project
        name: GunsNAmmo info
        version: 0.0.1
logging:
    level:
        org:
            springframework: DEBUG
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
management:
    endpoints:
        jmx:
            exposure:
                include: health,info,env,beans
        web:
            exposure:
                include: health,info,env,beans
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
    port: 8080
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
